// Embedded "large" airport + runway dataset for the radar runway overlay.
//
// Source: OurAirports (public domain, https://ourairports.com/data/), filtered to
// large_airport rows. Generated by ESP32-Plane-Radar's scripts/build_large_airports.py
// (MIT, (c) 2026 MatixYo) and vendored here verbatim -- see radar_view.hh for attribution.
// Do not edit by hand; regenerate from the upstream script if the dataset changes.
//
// Coordinates are stored as int32 degrees x 1e7 (e7). Airports and runways are POD arrays
// placed in .rodata (memory-mapped flash on the ESP32-S3), so the ~55 KB blob costs flash,
// not DRAM. Runway.airport_idx indexes kAirports[].
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::large_airports {

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
};

struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
};

constexpr size_t kAirportCount = 1166;
constexpr size_t kRunwayCount = 1706;

extern const Airport kAirports[];
extern const Runway kRunways[];

}  // namespace data::large_airports
