#!/usr/bin/env python3
"""Convert images/adsbee_logo.png into an RGB565 C array for the GC9A01 boot splash.

Regenerate splash_data.cpp/.hh whenever images/adsbee_logo.png changes:
    python3 firmware/scripts/gen_splash_image.py

Requires Pillow (`pip install Pillow`).
"""

import pathlib
import sys

from PIL import Image

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE_PNG = REPO_ROOT / "images" / "adsbee_logo.png"
OUT_DIR = REPO_ROOT / "firmware/adsbee_1090/esp/main/peripherals/display"

# The GC9A01 is a 240x240 round panel. The source logo has wide whitespace margins, so a plain
# cover-fit leaves the bee looking small. ZOOM scales the logo before the center-crop to control
# how large the subject appears:
#   ZOOM = 1.0  -> cover-fit (logo exactly fills the 240 box; sides cropped, bee looks small)
#   ZOOM > 1.0  -> zoom in: bee bigger, more of the edges cropped away
#   ZOOM < 1.0  -> zoom out: bee smaller, white margin padded around it
# Bump this up to make the bee bigger, down to show more of the logo. Corners are masked by the
# circular bezel, so cropping there is free.
ZOOM = 0.60
TARGET_WIDTH = 240
TARGET_HEIGHT = 240

# Logo background color, used to pad when ZOOM < 1.0 leaves uncovered edges (source bg is white).
BACKGROUND_RGB = (255, 255, 255)


def main() -> int:
    im = Image.open(SOURCE_PNG).convert("RGB")

    # Cover scale fills the box; ZOOM scales relative to that. Resize the whole logo, then paste it
    # centered onto a TARGET_WIDTH x TARGET_HEIGHT canvas -- cropping the overflow when it is larger
    # than the canvas, padding with BACKGROUND_RGB when smaller.
    cover_scale = max(TARGET_WIDTH / im.width, TARGET_HEIGHT / im.height)
    scale = cover_scale * ZOOM
    resized = im.resize(
        (round(im.width * scale), round(im.height * scale)), Image.LANCZOS
    )

    canvas = Image.new("RGB", (TARGET_WIDTH, TARGET_HEIGHT), BACKGROUND_RGB)
    offset = (
        (TARGET_WIDTH - resized.width) // 2,
        (TARGET_HEIGHT - resized.height) // 2,
    )
    canvas.paste(resized, offset)
    im = canvas
    target_height = TARGET_HEIGHT

    # Iterate the raw RGB byte triples rather than im.getdata() (deprecated in Pillow, and its
    # replacement is too new to rely on given our Pillow>=10 floor). tobytes() is stable and fast.
    raw = im.tobytes()  # R,G,B per pixel, row-major.
    values = []
    for i in range(0, len(raw), 3):
        r, g, b = raw[i], raw[i + 1], raw[i + 2]
        values.append(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3))

    hh_path = OUT_DIR / "splash_data.hh"
    cpp_path = OUT_DIR / "splash_data.cpp"

    hh_path.write_text(f"""\
// Embedded boot splash image (images/adsbee_logo.png), scaled to fit the GC9A01's 240px
// circular viewport. Generated by firmware/scripts/gen_splash_image.py -- do not edit by
// hand; regenerate from the source PNG if it changes.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::splash {{

constexpr int kWidth = {TARGET_WIDTH};
constexpr int kHeight = {target_height};

// RGB565 pixels, row-major, {TARGET_WIDTH}x{target_height}.
extern const uint16_t kImage[{len(values)}];

}}  // namespace data::splash
""")

    with cpp_path.open("w") as f:
        f.write(
            "// Embedded boot splash image data. Generated by "
            "firmware/scripts/gen_splash_image.py from images/adsbee_logo.png -- do not "
            "edit by hand.\n"
            "#ifdef WITH_DISPLAY\n\n"
            '#include "splash_data.hh"\n\n'
            "namespace data::splash {\n\n"
            f"const uint16_t kImage[{len(values)}] = {{\n"
        )
        for i in range(0, len(values), 12):
            row = values[i : i + 12]
            f.write("    " + ", ".join(f"0x{v:04x}" for v in row) + ",\n")
        f.write("};\n\n}  // namespace data::splash\n\n#endif  // WITH_DISPLAY\n")

    print(
        f"Wrote {hh_path} and {cpp_path} ({TARGET_WIDTH}x{target_height}, {len(values)} pixels)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
