#!/bin/bash
# ADSBee firmware build script.
# Builds all three firmware targets (ESP32, TI CC1312, RP2040 Pico) using Docker containers.
# Usage: ./build.sh [-d] [-f] [--display] [target] [test_filter]
#   targets: all (default), esp, ti, pico, test, clean
#   -d: build in Debug mode instead of Release
#   -f: force coprocessor reflash by stamping a per-build cache-buster into the firmware version, so the
#       RP2040 reflashes the ESP32/CC1312 on next boot even if the release-candidate wasn't bumped (dev only)
#   --display: build the optional GC9A01 round display support (OFF by default). Can also be enabled
#       persistently by exporting WITH_DISPLAY=1. NOTE: toggling this changes the ESP32 binary but not
#       the firmware version, so pair it with -f (or bump the version) to force the coprocessor reflash.
#   test_filter: optional regex passed to ctest -R when target is "test" (e.g. "AircraftJSON")

set -e

script_dir="$(cd "$(dirname "$0")" && pwd)"
cd "$script_dir"

# Number of parallel build jobs.
jobs=$(nproc 2>/dev/null || echo 4)
required_esp_idf_version="v5.5.2"

debug=false
force_esp_reflash=false
# Optional GC9A01 display support (WITH_DISPLAY). OFF by default; seed from the environment so it can be
# enabled persistently with `export WITH_DISPLAY=1`, then let the --display/--no-display flags override.
with_display=false
case "${WITH_DISPLAY:-}" in 1 | on | ON | true | TRUE | yes | YES) with_display=true ;; esac
while [ $# -gt 0 ]; do
    case "$1" in
        -d) debug=true; shift ;;
        -f | --force-esp-reflash) force_esp_reflash=true; shift ;;
        --display) with_display=true; shift ;;
        --no-display) with_display=false; shift ;;
        *) break ;;
    esac
done
test_filter="${2:-}"

# CMake ON/OFF value threaded into every target's configure step so the display setting is consistent
# across the ESP32, RP2040, and host builds (the shared Settings struct fields are unguarded, so this
# only toggles the AT+DISPLAY_* commands and their settings-dump lines -- never the SPI struct layout).
with_display_cmake=$( [ "$with_display" = true ] && echo ON || echo OFF )
echo "=== Display support (WITH_DISPLAY): $with_display_cmake ==="

# Path to the gitignored cache-buster header #included by common/coprocessor/object_dictionary.cpp.
build_id_header="$script_dir/../common/coprocessor/firmware_build_id.hh"

# Write the cache-buster header. With -f, stamp in the current epoch seconds so kFirmwareVersion changes
# every build (forcing a coprocessor reflash); otherwise write 0 so normal release-candidate versioning
# applies. The same value is used for every processor in a single run, so images agree after flashing but
# a later rebuild triggers a reflash. Changing the header content also re-triggers compilation of
# object_dictionary.cpp in every container, so the new value can't be masked by a stale build cache.
write_build_id_header() {
    local build_id=0
    if [ "$force_esp_reflash" = true ]; then
        build_id=$(date +%s)
        echo "=== Forcing coprocessor reflash (cache-buster build id: $build_id) ==="
    fi
    cat > "$build_id_header" <<EOF
// AUTO-GENERATED by build.sh. Do not edit or commit (gitignored).
// 0 = normal versioning; nonzero = per-build cache-buster forcing a coprocessor reflash (build.sh -f).
#pragma once
#define ADSBEE_FORCE_REFLASH_BUILD_ID $build_id
EOF
}

# Verify the Settings/firmware version sync rule (see firmware/scripts/check_version_sync.sh).
# Compares the committed state (HEAD) against the working tree.
check_version_sync() {
    "$script_dir/../scripts/check_version_sync.sh" HEAD WORKTREE
}

check_esp_idf_version() {
    echo "=== Checking ESP-IDF version (required: $required_esp_idf_version) ==="
    local idf_version
    idf_version=$(docker compose run --rm esp-idf bash -c "idf.py --version")
    echo "ESP-IDF reported by container: $idf_version"
    if [[ "$idf_version" != *"$required_esp_idf_version"* ]]; then
        echo "ERROR: ESP-IDF version mismatch. Expected $required_esp_idf_version."
        echo "Update compose.yml to pin the esp-idf image tag to $required_esp_idf_version."
        exit 1
    fi
}

# Generate the GC9A01 boot-splash C array from images/adsbee_logo.png. Runs on the host because
# the ESP-IDF container has no Pillow. The generated esp/main/peripherals/display/splash_data.{hh,cpp}
# are gitignored build artifacts that display.cpp #includes; regenerating every ESP build means a
# changed PNG (or ZOOM in the script) is always picked up. See firmware/README.md.
generate_splash() {
    local gen="$script_dir/../scripts/gen_splash_image.py"
    local venv_py="$script_dir/../../.venv/bin/python3"
    local py="python3"
    [ -x "$venv_py" ] && py="$venv_py"
    echo "=== Generating boot-splash image data ==="
    if ! "$py" -c "import PIL" 2>/dev/null; then
        echo "ERROR: Pillow (PIL) is required to generate the boot-splash image but is not available to '$py'."
        echo "       Install it with 'just flash-deps' (or 'pip install Pillow') and re-run the build."
        exit 1
    fi
    "$py" "$gen"
}

build_esp() {
    check_esp_idf_version
    # The boot-splash asset is only #included by the (guarded) display sources, so a non-display
    # build neither needs it nor should require Pillow to be installed.
    if [ "$with_display" = true ]; then
        generate_splash
    fi
    if [ "$debug" = true ]; then
        echo "=== Building ESP32-S3 firmware (Debug) ==="
        # sdkconfig_debug is auto-generated on first run by layering sdkconfig.debug on top of sdkconfig.
        # Delete esp/sdkconfig_debug to force regeneration (e.g. after base sdkconfig changes).
        docker compose run --rm esp-idf bash -c "
            cd /firmware/adsbee_1090/esp &&
            idf.py -B build/Debug -D WITH_DISPLAY=$with_display_cmake -D CMAKE_BUILD_TYPE=Debug -D SDKCONFIG=\"\$(pwd)/sdkconfig_debug\" -D \"SDKCONFIG_DEFAULTS=\$(pwd)/sdkconfig;\$(pwd)/sdkconfig.debug\" build
        "
        echo "=== ESP32-S3 build complete (Debug): esp/build/Debug/adsbee_esp.bin ==="
    else
        echo "=== Building ESP32-S3 firmware ==="
        docker compose run --rm esp-idf bash -c "
            cd /firmware/adsbee_1090/esp &&
            idf.py -B build/Release -D WITH_DISPLAY=$with_display_cmake build
        "
        echo "=== ESP32-S3 build complete: esp/build/Release/adsbee_esp.bin ==="
    fi
}

build_ti() {
    local build_type=$( [ "$debug" = true ] && echo "Debug" || echo "Release" )
    echo "=== Building TI CC1312 firmware ($build_type) ==="
    docker compose run --rm ti-lpf2 bash -c "
        cd /firmware/adsbee_1090/ti/sub_ghz_radio &&
        mkdir -p build && cd build &&
        cmake -DCMAKE_BUILD_TYPE=$build_type \
              -DCMAKE_C_COMPILER=/usr/bin/arm-none-eabi-gcc \
              -DCMAKE_CXX_COMPILER=/usr/bin/arm-none-eabi-g++ .. &&
        cmake --build . --config $build_type --target all -j $jobs
    "
    echo "=== TI CC1312 build complete: ti/sub_ghz_radio/build/sub_ghz_radio.bin ==="
}

build_pico() {
    local build_type=$( [ "$debug" = true ] && echo "Debug" || echo "Release" )
    echo "=== Building RP2040 Pico firmware ($build_type) ==="
    # Check that ESP32 and TI firmware exist.
    local esp_build_dir=$( [ "$debug" = true ] && echo "esp/build/Debug" || echo "esp/build/Release" )
    if [ ! -f $esp_build_dir/adsbee_esp.bin ]; then
        echo "ERROR: $esp_build_dir/adsbee_esp.bin not found. Run ESP32 build first."
        exit 1
    fi
    if [ ! -f ti/sub_ghz_radio/build/sub_ghz_radio.bin ]; then
        echo "ERROR: ti/sub_ghz_radio/build/sub_ghz_radio.bin not found. Run TI build first."
        exit 1
    fi
    docker compose run --rm pico-docker bash -c "
        cd /firmware/adsbee_1090/pico &&
        mkdir -p build/$build_type && cd build/$build_type &&
        cmake -DCMAKE_BUILD_TYPE=$build_type \
              -DWITH_DISPLAY=$with_display_cmake \
              -DCMAKE_C_COMPILER=/usr/bin/arm-none-eabi-gcc \
              -DCMAKE_CXX_COMPILER=/usr/bin/arm-none-eabi-g++ ../.. &&
        cmake --build . --config $build_type --target all -j $jobs
    "
    echo "=== RP2040 Pico build complete ==="
    echo "  Firmware: pico/build/$build_type/application/combined.uf2"
    echo "  OTA:      pico/build/$build_type/application/adsbee_1090.ota"
}

build_test() {
    local filter="${1:-}"
    local ctest_filter_opt=""
    if [ -n "$filter" ]; then
        ctest_filter_opt="-R $filter"
        echo "=== Building and running host tests (filter: $filter) ==="
    else
        echo "=== Building and running host tests ==="
    fi
    docker compose run --rm pico-docker bash -c "
        cd /firmware/modules/googletest &&
        mkdir -p build && cd build &&
        cmake -DBUILD_SHARED_LIBS=ON .. &&
        make -j $jobs &&
        cd /firmware/adsbee_1090/pico &&
        mkdir -p build/Test && cd build/Test &&
        cmake -DCMAKE_BUILD_TYPE=Test \
              -DWITH_DISPLAY=$with_display_cmake \
              -DCMAKE_C_COMPILER=/usr/bin/gcc \
              -DCMAKE_CXX_COMPILER=/usr/bin/g++ ../.. &&
        make -j $jobs &&
        ctest --verbose $ctest_filter_opt
    "
    echo "=== Host tests complete ==="
}

clean_builds() {
    echo "=== Cleaning build directories ==="
    rm -rf esp/build
    rm -rf esp/sdkconfig_debug
    rm -rf ti/sub_ghz_radio/build
    rm -rf pico/build
    echo "=== Clean complete ==="
}

target="${1:-all}"

if [ "$target" != "clean" ]; then
    check_version_sync
    write_build_id_header
fi

case "$target" in
    esp)
        build_esp
        ;;
    ti)
        build_ti
        ;;
    pico)
        build_pico
        ;;
    test)
        build_test "$test_filter"
        ;;
    clean)
        clean_builds
        ;;
    all)
        build_type=$( [ "$debug" = true ] && echo "Debug" || echo "Release" )
        build_esp
        build_ti
        build_pico
        echo ""
        echo "=== Full build complete! ==="
        echo "  Output: firmware/pico/build/$build_type/application/combined.uf2"
        ;;
    *)
        echo "Usage: $0 [-d] [-f] [--display] [esp|ti|pico|test|clean|all]"
        echo "  -d        - Build in Debug mode instead of Release"
        echo "  --display - Build the optional GC9A01 display support (OFF by default; or WITH_DISPLAY=1)"
        echo "  all   - Build all firmware targets (default)"
        echo "  esp   - Build ESP32-S3 firmware only"
        echo "  ti    - Build TI CC1312 firmware only"
        echo "  pico  - Build RP2040 Pico firmware only (requires esp + ti first)"
        echo "  test [filter] - Build and run host unit tests; optional filter is a ctest -R regex (e.g. \"AircraftJSON\")"
        echo "  clean - Remove all build directories"
        exit 1
        ;;
esac
